#' R/example_sim_data.R
#'
#' Simulated treatment and control outcomes for six endpoints generated by
#' `simulate_example_one_stage_data()`.
#'
#' @name example_sim_data
#' @title Example simulated datasets
#' @docType data
#' @keywords datasets
#' @aliases sim1 sim2
#' @usage data(sim1); data(sim2)
#' @format Each object (\code{sim1}, \code{sim2}) is a list with two numeric matrices
#' \describe{
#'   \item{y_trt}{Numeric matrix (n_trt x 6); treatment outcomes.}
#'   \item{y_ct}{Numeric matrix (n_ct x 6); control outcomes.}
#' }
#' @details Generated with the parameters shown in \code{data-raw/example_sim_data.R}.
#' - \code{sim1}: 29 per arm, seed = 42.
#' - \code{sim2}: 61 per arm, seed = 58.
#'
#' @source Generated using internal package function \code{simulate_example_one_stage_data()}.
#' @examples
#' data(sim1)
#' data(sim2)
#' str(sim1)
#' str(sim2)
"sim1"
"sim2"
NULL
